###
GET http://localhost:8080/api/v1/swaps/1634744252240
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyZW0wMjlAeWFob28uY29tIiwiaWF0IjoxNjM0OTc1ODkzfQ.z7hJnHD9OGoq56ADl0FErqNzh5bsRxN5hWXgkarjpBA